In [1]:
import pandas as pd
import numpy as np
import os
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
manufacturer_df = pd.read_csv("../Resources/manufacturer_breakdown.csv")
manufacturer_df = manufacturer_df[['location','date','CanSino','Johnson&Johnson','Moderna','Oxford/AstraZeneca','Pfizer/BioNTech','Sinopharm/Beijing','Sinovac','Sputnik V']]

In [19]:
manufacturer_df.head(50)

,location,date,CanSino,Johnson&Johnson,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,Sinovac,Sputnik V
0,Austria,2021-01-08,NaN,0.0,0.0,0.0,31099.0,NaN,NaN,NaN
1,Austria,2021-01-15,NaN,0.0,87.0,0.0,115801.0,NaN,NaN,NaN
2,Austria,2021-01-22,NaN,0.0,304.0,1.0,212899.0,NaN,NaN,NaN
3,Austria,2021-01-29,NaN,0.0,4225.0,2.0,257621.0,NaN,NaN,NaN
4,Austria,2021-02-05,NaN,0.0,5922.0,6.0,353111.0,NaN,NaN,NaN
5,Austria,2021-02-12,NaN,0.0,10009.0,10766.0,454563.0,NaN,NaN,NaN
6,Austria,2021-02-19,NaN,0.0,14132.0,43472.0,520127.0,NaN,NaN,NaN
7,Austria,2021-02-26,NaN,0.0,22495.0,101160.0,581222.0,NaN,NaN,NaN
8,Austria,2021-03-05,NaN,0.0,31795.0,155994.0,685651.0,NaN,NaN,NaN
9,Austria,2021-03-12,NaN,0.0,47139.0,234638.0,848297.0,NaN,NaN,NaN
10,Austria,2021-03-19,NaN,18.0,78908.0,307848.0,980824.0,NaN,NaN,NaN
11,Austria,2021-03-26,NaN,32.0,104255.0,383177.0,1127139.0,NaN,NaN,NaN
12,Austria,2021-04-02,NaN,55.0,140582.0,421729.0,1275205.0,NaN,NaN,NaN
13,Austria,2021-04-09,NaN,99.0,180087.0,512110.0,1496385.0,NaN,NaN,NaN
14,Austria,2021-04-16,NaN,109.0,222572.0,607999.0,1730058.0,NaN,NaN,NaN
15,Austria,2021-04-23,NaN,114.0,259859.0,656941.0,1993639.0,NaN,NaN,NaN
16,Austria,2021-04-30,NaN,381.0,298802.0,699374.0,2267104.0,NaN,NaN,NaN
17,Austria,2021-05-07,NaN,6509.0,348094.0,762359.0,2597491.0,NaN,NaN,NaN
18,Austria,2021-05-14,NaN,13507.0,397993.0,826519.0,2896941.0,NaN,NaN,NaN
19,Austria,2021-05-21,NaN,25803.0,465986.0,904299.0,3274753.0,NaN,NaN,NaN
20,Austria,2021-05-28,NaN,37967.0,519579.0,987190.0,3610163.0,NaN,NaN,NaN
21,Austria,2021-06-04,NaN,58260.0,574990.0,1055842.0,4035688.0,NaN,NaN,NaN
22,Austria,2021-06-11,NaN,79937.0,637992.0,1151265.0,4474462.0,NaN,NaN,NaN
23,Austria,2021-06-18,NaN,94893.0,687637.0,1203754.0,4929409.0,NaN,NaN,NaN
24,Austria,2021-06-25,NaN,103454.0,743413.0,1277766.0,5374506.0,NaN,NaN,NaN
25,Austria,2021-07-02,NaN,128892.0,803487.0,1385677.0,5765676.0,NaN,NaN,NaN
26,Austria,2021-07-09,NaN,152963.0,853888.0,1453630.0,6092727.0,NaN,NaN,NaN
27,Austria,2021-07-16,NaN,172227.0,898380.0,1505392.0,6364751.0,NaN,NaN,NaN
28,Austria,2021-07-23,NaN,188745.0,944860.0,1535225.0,6612672.0,NaN,NaN,NaN
29,Austria,2021-07-30,NaN,200788.0,963749.0,1561869.0,6822203.0,NaN,NaN,NaN
30,Austria,2021-08-06,NaN,215893.0,981526.0,1577413.0,6998746.0,NaN,NaN,NaN
31,Austria,2021-08-13,NaN,226125.0,990952.0,1583366.0,7122891.0,NaN,NaN,NaN
32,Austria,2021-08-20,NaN,239445.0,1004904.0,1586724.0,7215247.0,NaN,NaN,NaN
33,Austria,2021-08-27,NaN,253071.0,1008540.0,1588984.0,7272810.0,NaN,NaN,NaN
34,Austria,2021-09-03,NaN,265809.0,1013268.0,1591349.0,7321020.0,NaN,NaN,NaN
35,Austria,2021-09-10,NaN,279596.0,1016094.0,1592819.0,7370465.0,NaN,NaN,NaN
36,Austria,2021-09-17,NaN,290763.0,1019963.0,1594154.0,7428881.0,NaN,NaN,NaN
37,Austria,2021-09-24,NaN,304150.0,1022148.0,1595602.0,7481747.0,NaN,NaN,NaN
38,Austria,2021-09-28,NaN,308770.0,1023178.0,1596245.0,7513162.0,NaN,NaN,NaN
39,Belgium,2021-01-08,NaN,0.0,0.0,0.0,28032.0,NaN,NaN,NaN
40,Belgium,2021-01-15,NaN,0.0,37.0,0.0,126887.0,NaN,NaN,NaN
41,Belgium,2021-01-22,NaN,0.0,4500.0,0.0,244657.0,NaN,NaN,NaN
42,Belgium,2021-01-29,NaN,0.0,6193.0,0.0,334334.0,NaN,NaN,NaN
43,Belgium,2021-02-05,NaN,0.0,15947.0,0.0,463411.0,NaN,NaN,NaN
44,Belgium,2021-02-12,NaN,0.0,25531.0,359.0,598937.0,NaN,NaN,NaN
45,Belgium,2021-02-19,NaN,0.0,30326.0,10768.0,699581.0,NaN,NaN,NaN
46,Belgium,2021-02-26,NaN,0.0,32790.0,45316.0,788203.0,NaN,NaN,NaN
47,Belgium,2021-03-05,NaN,0.0,51618.0,110077.0,877249.0,NaN,NaN,NaN
48,Belgium,2021-03-12,NaN,0.0,67532.0,191223.0,973684.0,NaN,NaN,NaN
49,Belgium,2021-03-19,NaN,0.0,89998.0,351029.0,1084065.0,NaN,NaN,NaN

In [20]:
manufacturer_df.fillna(int(0))

,location,date,CanSino,Johnson&Johnson,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,Sinovac,Sputnik V
0,Austria,2021-01-08,0.0,0.0,0.0,0.0,31099.0,0.0,0.0,0.0
1,Austria,2021-01-15,0.0,0.0,87.0,0.0,115801.0,0.0,0.0,0.0
2,Austria,2021-01-22,0.0,0.0,304.0,1.0,212899.0,0.0,0.0,0.0
3,Austria,2021-01-29,0.0,0.0,4225.0,2.0,257621.0,0.0,0.0,0.0
4,Austria,2021-02-05,0.0,0.0,5922.0,6.0,353111.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4962,Uruguay,2021-09-26,0.0,0.0,0.0,86603.0,1958109.0,0.0,3245853.0,0.0
4963,Uruguay,2021-09-27,0.0,0.0,0.0,86603.0,1964999.0,0.0,3245876.0,0.0
4964,Uruguay,2021-09-28,0.0,0.0,0.0,86603.0,1967911.0,0.0,3245896.0,0.0
4965,Uruguay,2021-09-29,0.0,0.0,0.0,86603.0,1969968.0,0.0,3245907.0,0.0
4966,Uruguay,2021-09-30,0.0,0.0,0.0,86603.0,1972562.0,0.0,3245928.0,0.0

In [ ]:
cumulative_manufacturer_df = manufacturer_df